# Generated by Django 5.0.6 on 2024-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logined',
            field=models.BooleanField(default=False),
        ),
    ]
