# Generated by Django 5.0.6 on 2024-06-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_is_logined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_logined',
            new_name='is_logined_ad',
        ),
    ]
