# Generated by Django 5.0.6 on 2024-06-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_is_logined_user_is_logined_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_logined_ad',
        ),
    ]
